stages:
  - notify

telegram_notification:
  stage: notify
  image: curlimages/curl:latest
  script:
    - export MESSAGE="Nuevo push (REPOSITORIO $CI_PROJECT_URL) (AUTOR $(echo $CI_COMMIT_AUTHOR | cut -d' ' -f1,2)) (RAMA $CI_COMMIT_REF_NAME) (COMMIT $CI_COMMIT_MESSAGE) (URL $CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA)"
    - curl -s -X POST https://api.telegram.org/bot$BotTELEGRAM_TOKEN/sendMessage -d chat_id=$CHAT_ID -d text="${MESSAGE}" >> /dev/null
  only:
    - master
    - dev
