stages:
  - notify

telegram_notification:
  stage: notify
  image: curlimages/curl:latest
  script:
    # - export MESSAGE="Nuevo push en el repo $CI_PROJECT_URL de $(echo $CI_COMMIT_AUTHOR | cut -d' ' -f1,2) en la rama $CI_COMMIT_REF_NAME, commit $CI_COMMIT_MESSAGE -> $CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA"
    - export MESSAGE="Nuevo push en el repo $CI_PROJECT_URL de $(echo $CI_COMMIT_AUTHOR | cut -d' ' -f1,2) en la rama $CI_COMMIT_REF_NAME, commit <a href='$CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA'>$(printf '%s' "$CI_COMMIT_MESSAGE" | sed 's/\x27/\&apos;/g' | sed 's/\x22/\&quot;/g')</a> -> $CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA"
    - curl -s -X POST https://api.telegram.org/bot$BotTELEGRAM_TOKEN/sendMessage -d chat_id=$CHAT_ID -d text="${MESSAGE}" >> /dev/null
  only:
    - master
