stages:
  - notify

telegram_notification:
  stage: notify
  image: curlimages/curl:latest
  script:
    - export MESSAGE="Se ha realizado un nuevo push en la rama ${CI_COMMIT_REF_NAME}, el mensaje del commit es: ${CI_COMMIT_MESSAGE} y el enlace al commit es ${CI_COMMIT_URL}."
    - curl -s -X POST https://api.telegram.org/bot5954860043:AAE_3WJgDxYUGZb8A5-Kmsycsj6cWFc2ytw/sendMessage -d chat_id=-849254269 -d text="${MESSAGE}" >> /dev/null
  only:
    - master
