name: Telegram Notifications

on: [push]

jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
    - name: Send notifications to Telegram
      run: curl -s -X POST https://api.telegram.org/bot5954860043:AAE_3WJgDxYUGZb8A5-Kmsycsj6cWFc2ytw/sendMessage -d chat_id=-849254269 -d text="${MESSAGE}" >> /dev/null
      env:
        #MESSAGE: "Se ha realizado un nuevo push en la rama ${{ github.ref }} con el commit ${{ github.sha }}."
        #MESSAGE: "Se ha realizado un nuevo push en la rama [$GITHUB_REF](${{ github.event.compare }}) con el commit [$GITHUB_SHA](${{ github.event.head_commit.url }})."
        MESSAGE: "Se ha realizado un nuevo push en la rama XXX con el commit ${{ github.event.head_commit.url }}."
