name: Telegram Notifications

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set COMMIT_MESSAGE variable
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
      - name: Send notifications to Telegram
        run: curl -s -X POST https://api.telegram.org/bot5954860043:AAE_3WJgDxYUGZb8A5-Kmsycsj6cWFc2ytw/sendMessage -d chat_id=-849254269 -d text="${MESSAGE}" >> /dev/null
        env:
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          MESSAGE: "Se ha realizado un nuevo push en la rama XXX con el commit ${{ env.COMMIT_MESSAGE }} > ${{ github.event.head_commit.url }}."
