name: Telegram Notifications

on:
  push:
    branches: [ master ]

jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
    - name: Send notifications to Telegram
      run: curl -s -X POST https://api.telegram.org/bot5954860043:AAE_3WJgDxYUGZb8A5-Kmsycsj6cWFc2ytw/sendMessage -d chat_id=-849254269 -d text="${MESSAGE}" >> /dev/null
      env:
        message: 'Se ha realizado un nuevo push en la rama ${{ env.GITHUB_REF }} con el commit ${{ env.GITHUB_SHA }}.'
